// Questo file ci consente, attraverso l'estensione REST client di inviare richieste
// al nostro web service

get http://127.0.0.1:3000
###
post http://127.0.0.1:3000/init
Content-Type: application/json

{
    "initPassword": "12345",
    "adminPassword": "cisco"
}

###
post http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "cisco"
}

###
get http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0NDIyMTY5LCJleHAiOjE3MzQ0MjU3Njl9.ZeMyRvP48IKio-k_rphE6dP0I4fSOd0wgilNVv_9AE4
Content-Type: application/json

###
post http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0NDIyMTY5LCJleHAiOjE3MzQ0MjU3Njl9.ZeMyRvP48IKio-k_rphE6dP0I4fSOd0wgilNVv_9AE4
Content-Type: application/json

{
    "username": "pippo",
    "password": "pippo",
    "role": "user",
    "ghgjgjgjh": "jkljkljl",
    "cell": "236782482"
}

put http://127.0.0.1:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0NDIyMTY5LCJleHAiOjE3MzQ0MjU3Njl9.ZeMyRvP48IKio-k_rphE6dP0I4fSOd0wgilNVv_9AE4
Content-Type: application/json

{
    "surname": "pluto"
}