// Questo file ci consente, attraverso l'estensione REST client di inviare richieste
// al nostro web service

get http://127.0.0.1:3000
###
post http://127.0.0.1:3000/init
Content-Type: application/json

{
    "initpassword": "12345",
    "adminpassword": "cisco"
}